#!/bin/bash

clear
echo -e "================================================="
echo -e "# Script Auto Install SSH & OpenVPN             #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 32 bit & 64 bit                  #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Modified Admin VPNSTORES                              #"
echo -e "#-----------------------------------------------#"
echo -e "Thanks To"
echo -e "---------"
echo -e "Allah"
echo -e "My Family"
echo -e "Google"
echo -e "Admin Portal & White Vps"
echo -e "VPNSTORES.NET"
echo -e ""
echo -e "#-----------------------------------------------#"
echo -e "================================================="
